### ISSUE TITLE
编译失败了..

### ISSUE THREAD

**Issue by Adonis-Song** [bookzhan/bzijkPlayer#4]
大佬，我下下来工程后，build 失败提示
  CMake Error in CMakeLists.txt:
    The CMAKE_C_COMPILER:
![image](https://user-images.githubusercontent.com/34226411/125552508-ed04d3ec-b19a-48d1-94b8-dfc464c33dfe.png)

大佬有没有遇到过这种问题

**Comment by bookzhan** [comment]
是由于Android Studio与gradle版本的问题，这个用到gradle太老了，我已经升级了你重新下载就可以编译了，我现在用的Android Studio是4.2.2，ndkVersion 是'22.1.7171670'

**Comment by Adonis-Song** [comment]
感谢大佬，解决了，我发现clang的路径被指向了不知道什么鬼地方，然后我再build.gradle 中设置了ndkpath，就ok了，感谢大佬
